name = "Hugo Agency Theme"
license = "Apache License 2.0"
licenselink = "https://github.com/digitalcraftsman/hugo-agency-theme/blob/master/LICENSE/"
description = "A one page portfolio for companies and freelancers."
homepage = "https://github.com/digitalcraftsman/hugo-agency-theme/"
tags = ["portfolio", "company", "contact form", "clients", "team"]
features = ["portfolio with modals", "contact form", "timeline"]
min_version = 0.13

[author]
  name = "digitalcraftsman"
  homepage = "https://github.com/digitalcraftsman/"

# If porting an existing theme
[original]
  name = "David Miller"
  homepage = "http://www.ironsummitmedia.com/"
  repo = "https://github.com/IronSummitMedia/startbootstrap-agency/"
